#!/usr/bin/python
# -*- coding: utf-8

#######################################################################
# Copyright 2010 Signove Corporation - All rights reserved.
# Contact: Signove Corporation (contact@signove.com)
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of version 2.1 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330,
# Boston, MA 02111-1307  USA
#
# If you have questions regarding the use of this file, please contact
# Signove at contact@signove.com.
#######################################################################

import os.path
import sys
import time
import termios

import glib
import gobject
import dbus
import dbus.mainloop.glib
import dbus.exceptions
import dbus.service

from fcntl import ioctl
from ctypes import c_long


# PTS suite specs
hdp_snk_con = { 'TC_SNK_CON_BV_01_I': ( 'create_app_sink',
										'destroy_app'),
				'TC_SNK_CON_BV_02_I': ( 'create_app_sink',
										'destroy_app'),
				'TC_SNK_CON_BV_03_I': ( 'create_app_sink',
										'destroy_app'),
				'TC_SNK_CON_BV_04_I': ( 'pair',
										'create_app_sink',
										'create_channel_any',
										'destroy_channel',
										'destroy_app'),
				'TC_SNK_CON_BV_05_I': ('create_app_sink', 'destroy_app'),
				'TC_SNK_CON_BV_06_I': ( 'create_app_sink',
										'create_channel_any'),
				'TC_SNK_CON_BV_07_I': ( 'discover', ),
				'TC_SNK_CON_BV_08_I': ( 'delete_pairing',
										'create_app_sink',
										'destroy_app'),
				'TC_SNK_CON_BV_09_I': ( 'create_app_sink',
										'create_channel_any',
										'destroy_channel',
										'destroy_app'),
				'TC_SNK_CON_BV_10_I': ( 'set_discoverable', ) }

hdp_src_suites = {}
hdp_snk_suites = {'SNK_CON': hdp_snk_con}
groups = {'SRC': hdp_src_suites,
		  'SNK': hdp_snk_suites}


class Rejected(dbus.DBusException):
	_dbus_error_name = "org.bluez.Error.Rejected"


class PairAgent(dbus.service.Object):

	def __init__(self, bus, path, obs):
		dbus.service.Object.__init__(self, bus, path)
		self.obs = obs

	@dbus.service.method("org.bluez.Agent",
					in_signature="", out_signature="")
	def Release(self):
		print 'Release'

	@dbus.service.method("org.bluez.Agent",
					in_signature="os", out_signature="")
	def Authorize(self, device, uuid):
		print "Authorize (%s, %s)" % (device, uuid)
		authorize = raw_input("Authorize connection (yes/no): ")
		if (authorize == "yes"):
			return
		raise Rejected("Connection rejected by user")

	@dbus.service.method("org.bluez.Agent",
					in_signature="o", out_signature="s")
	def RequestPinCode(self, device):
		print "RequestPinCode (%s)" % (device)
		pin = raw_input("Enter PIN Code: ")
		return pin

	@dbus.service.method("org.bluez.Agent",
					in_signature="o", out_signature="u")
	def RequestPasskey(self, device):
		print "RequestPasskey (%s)" % (device)
		passkey = raw_input("Enter passkey: ")
		return dbus.UInt32(passkey)

	@dbus.service.method("org.bluez.Agent",
					in_signature="ou", out_signature="")
	def DisplayPasskey(self, device, passkey):
		print "DisplayPasskey (%s, %d)" % (device, passkey)

	@dbus.service.method("org.bluez.Agent",
					in_signature="ou", out_signature="")
	def RequestConfirmation(self, device, passkey):
		print "RequestConfirmation (%s, %d)" % (device, passkey)
		confirm = raw_input("Confirm passkey (yes/no): ")
		if (confirm == "yes"):
			return
		raise Rejected("Passkey doesn't match")

	@dbus.service.method("org.bluez.Agent",
					in_signature="s", out_signature="")
	def ConfirmModeChange(self, mode):
		print "ConfirmModeChange (%s)" % (mode)
		authorize = raw_input("Authorize mode change (yes/no): ")
		if (authorize == "yes"):
			return
		raise Rejected("Mode change by user")

	@dbus.service.method("org.bluez.Agent",
					in_signature="", out_signature="")
	def Cancel(self):
		print "Cancel"


class HDPAutoPTS:
	""" Runs an interactive prompt for automatically test BlueZ against PTS.
	"""
	def __init__(self, tests, mainloop):
		self.tests = tests
		self.mainloop = mainloop

		glib.io_add_watch(sys.stdin, glib.IO_IN | glib.IO_PRI, self.tick)


		self.bus = dbus.SystemBus()
		self.manager = dbus.Interface(self.bus.get_object("org.bluez", "/"),
				"org.bluez.Manager")
		self.hdp_manager = dbus.Interface(self.bus.get_object("org.bluez",
				"/org/bluez"), "org.bluez.HealthManager")
		self.agent = PairAgent(self.bus, '/test/agent', self)

		self.channels = []
		self.device = None
		self.app = None
		self.device_bdaddr = '00:80:98:E7:31:E1'
		self.select_adapter()

		self.test = None
		self.cmd_idx = -1

		self.device_found = 0
		self.discovering = False

	def select_adapter(self):
		select = self.manager.DefaultAdapter()
		adapters = self.manager.ListAdapters()

		print "Select an adapter [%s]:" % (select)
		i = 1
		for ad in adapters:
			print "\t%d. %s" % (i, ad)
			i = i + 1

		set = None
		while set == None:
			try:
				print 'Select: ',
				cmd = sys.stdin.readline()
				if cmd == '\n':
					print '\n'
					break
				pos = int(cmd) - 1
				if pos < 0:
					raise TypeError
				select = adapters[pos]
				set = True
			except (TypeError, IndexError, ValueError):
				print "Wrong selection, choose a device from the list."
			except KeyboardInterrupt:
				sys.exit()

		self.adapter = dbus.Interface(self.bus.get_object("org.bluez", select),
				"org.bluez.Adapter")
		self.bus.add_signal_receiver(self.device_found,
				dbus_interface="org.bluez.Adapter",
				signal_name="DeviceFound")
		self.bus.add_signal_receiver(self.property_changed,
				dbus_interface="org.bluez.Adapter",
				signal_name="PropertyChanged")

	def set_discoverable(self):
		self.adapter.SetProperty('Discoverable', dbus.Boolean(1))
		print 'Adapter set to General Discoverable mode...'

		cls = self.adapter.GetProperties()['Class']
		if cls != 0x4a0914:
			print 'WARNING: device class is not Health (0x4a0914). This test'\
			      ' might fail. Try \'sudo hciconfig <IFACE> class 0x4a0914\''
			print cls

	def select_device(self):
		devices = self.adapter.ListDevices()

		if len(devices) == 0:
			print "No devices available"
			sys.exit()

		print "Select a device [%s]:" % (devices[0])
		i = 1
		for dev in devices:
			print "%d. %s" % (i, dev)
			i = i + 1

		set = None
		select = devices[0]
		while set == None:
			try:
				print 'Select: ',
				cmd = sys.stdin.readline()
				if cmd == '\n':
					break
				pos = int(cmd) - 1
				if pos < 0:
					raise TypeError
				select = devices[pos]
				set = True
			except (TypeError, IndexError, ValueError):
				print "Wrong selection, try again: ",
			except KeyboardInterrupt:
				sys.exit()

		print "Connecting to", select
		self.device = dbus.Interface(self.bus.get_object("org.bluez", select),
						"org.bluez.HealthDevice")

	def pair(self):
		print 'Pairing..'
		self.pairing = True
		self.adapter.CreatePairedDevice(self.device_bdaddr, '/test/agent',
			'DisplayYesNo', reply_handler=self.pair_reply, error_handler=self.pair_error)

		slept = 0
		while self.pairing:
			time.sleep(1)
			slept += 1
			if slept >= 10:
				break

		self.pairing = False

	def delete_pairing(self):
		print 'Deleting pairing with %s' % self.device_bdaddr
		try:
			device = self.adapter.FindDevice(self.device_bdaddr)
			if device:
				self.adapter.RemoveDevice(device)
		except:
			pass
		print 'Pairing deleted. Input the PIN number whenever requested.'

	def device_found(self, addr, props):
		""" Receives DeviceFound signals, used for discovery.
		"""
		if not self.discovering:
			return

		if addr == self.device_bdaddr:
			print 'Device found! Confirm on PTS that it was found to continue.'
			self.discovering = False
			self.device_found = True
		else:
			print 'Found device', addr, 'ignoring...'

	def discover(self):
		print 'Discovering device...'
		self.discovering = True
		self.adapter.StartDiscovery()

		# Block cmd input until finished discovering or timeout (10s)
		slept = 0
		while self.discovering:
			time.sleep(1)
			slept += 1
			if slept >= 15:
				break

		print 'Discovering timed out. Next test will be ready to execute.'

	def property_changed(self, name, value):
		if name == 'Discovering' and not value:
			self.discovering = False
			if self.device_found:
				print 'Finished discovery, device was found. Confirm on PTS if'\
					  ' you haven\'t already.'

	def pair_reply(self, device):
		print 'Finished pairing with', device
		self.pairing = False

	def pair_error(self, error):
		print 'Failed to pair,', error
		self.pairing = False

	def create_app(self, role):
		self.app = self.hdp_manager.CreateApplication(
				{"DataType": dbus.types.UInt16(4103),
				 "Role": role})
		print 'Created app', self.app

	def create_app_sink(self):
		self.create_app('sink')

	def create_app_source(self):
		self.create_app('source')

	def destroy_app(self):
		print 'Destroying app'
		self.hdp_manager.DestroyApplication(self.app)
		self.app = None

	def create_channel(self, type):
		self.select_device()
		try:
			channel = self.device.CreateChannel(self.app, type)
			self.channels.append(channel)
		except dbus.exceptions.DBusException, e:
			print 'Failed to create channel. You might have selected the' \
				' wrong device or the test already passed, check PTS.', e

	def destroy_channel(self, channel=None):
		if not channel:
			if len(self.channels) == 0:
				return
			channel = self.channels[0]

		if not self.device or not self.channels:
			return
		chan = self.device.DestroyChannel(channel)
		self.channels.remove(channel)

	def list_channels(self):
		print '\n'.join(self.channels)

	def create_channel_any(self):
		self.create_channel("Any")

	def create_channel_reliable(self):
		self.create_channel('Reliable')

	def create_channel_streaming(self):
		self.create_channel('Streaming')

	def tick(self, src, cond):
		available = c_long()
		ioctl(src, termios.FIONREAD, available)
		ch = src.read(available.value)

		if ch.startswith('no'):# == 'y\n':
			self.skip()
		else:
			self.run()

		return True

	def next_cmd(self):
		cmds = self.test[1]
		cmd_idx = cmds.index(self.cmd)

		if cmd_idx + 1 == len(cmds):
			print 'Test finished'
			self.next_text()
		else:
			self.cmd = cmds[cmd_idx + 1]
			print 'Execute command %s ? (yes/no)' % self.cmd

	def next_text(self):
		test_idx = self.tests.index(self.test)
		if test_idx + 1 == len(self.tests):
			print 'Done!'
			raw_input('Hit enter to exit.')
			self.mainloop.quit()
		else:
			self.test = self.tests[test_idx + 1]
			print 'Run test %s ? (yes/no)' % self.test[0]

		self.cmd = None

	def run(self):
		if not self.test:
			self.test = self.tests[0]
			self.cmd = None
			print 'Run test %s ? (yes/no)' % self.test[0]
			return

		if not self.cmd:
			self.cmd = self.test[1][0]
			print 'Execute command %s ? (yes/no)' % self.cmd
			return

		try:
			getattr(self, self.cmd)()
			self.next_cmd()
		except Exception, e:
			print 'Failed to call command', e, self.cmd

	def skip(self):
		self.cmd = None
		print 'Bailing out test'
		self.next_text()

def get_tests(fname):
	tests = []
	names = [l.replace('\n', '') for l in open(fname, 'r').readlines() if not
			l.startswith('[')]

	print 'Matching selected tests...'

	for g in groups.values():
		for s in g.values():
			for test_name, test in s.items():
				if test_name in names:
					tests.append((test_name, test))

	tests.sort()
	print 'Tests matched:', ', '.join([t[0] for t in tests])
	return tests

def usage():
	print 'Usage: %s --list\t(list tests)' % sys.argv[0]
	print '       %s infile\t(run tests listed on infile)' % sys.argv[0]
	sys.exit(0)

def list_tests():
	for gname, g in groups.items():
		for sname, s in g.items():
			print '[Namespace [%s.%s]]' % (gname, sname)
			for test_name in s.keys():
				print test_name
	sys.exit(0)


if __name__ == '__main__':
	if len(sys.argv) != 2:
		usage()
	else:
		{'--list': list_tests,
		 '--help': usage,}.get(sys.argv[1], lambda: 1)()

	if not os.path.exists(sys.argv[1]):
		print 'Input file %s does not exist.' % sys.argv[1]
		sys.exit(0)

	dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

	mainloop = gobject.MainLoop()
	tests = get_tests(sys.argv[1])
	suite = HDPAutoPTS(tests, mainloop)

	try:
		mainloop.run()
	except KeyboardInterrupt:
		print 'Bye'
