#!/usr/bin/env python

MAX_APPS = 6
MAX_CHANNELS = 1 # per device/application
DISTINGUISH_APP = True
RENEW_APP = False
SINK_INITIATOR = True

# TODO do something different with Streaming channels


if not DISTINGUISH_APP:
	MAX_CHANNELS *= MAX_APPS # count by device, not by device*app

import sys
import os
import glib
import dbus
import socket
import dbus.service
import gobject
import random
import time
from dbus.mainloop.glib import DBusGMainLoop


DBusGMainLoop(set_as_default=True)
loop = gobject.MainLoop()
bus = dbus.SystemBus()


class MasterControl(object):
	def __init__(self):
		self.apps = []
		self.dot_count = 0
		self.sources = []
		self.sinks = []
		self.devices = {}

		self.channels = {}
		self.chan_dev_app = {}
		self.channel_sig = {}
		self.data_seq = 0
		self.accepted = []
		self.initiated = []
		self.sockets = {}

		self.retry_to = 0
		self.echo_pending = False

		obj = bus.get_object("org.bluez", "/org/bluez")
		self.hmanager = dbus.Interface(obj, "org.bluez.HealthManager")
		obj = bus.get_object("org.bluez", "/")
		self.manager = dbus.Interface(obj, "org.bluez.Manager") 

		bus.add_signal_receiver(self.ChannelConnected,
			signal_name="ChannelConnected",
			bus_name="org.bluez",
			path_keyword="device_path",
			interface_keyword="interface",
			dbus_interface="org.bluez.HealthDevice")

		bus.add_signal_receiver(self.ChannelDeleted,
			signal_name="ChannelDeleted",
			bus_name="org.bluez",
			path_keyword="device_path",
			interface_keyword="interface",
			dbus_interface="org.bluez.HealthDevice")

		bus.add_signal_receiver(self.DevicePropertyChanged,
			signal_name="PropertyChanged",
			bus_name="org.bluez",
			path_keyword="device_path",
			interface_keyword="interface",
			dbus_interface="org.bluez.HealthDevice")

		self.CreateApplications()

		if "-s" not in sys.argv:
			self.find_devices()

		# TODO move these magic values to top
		self.CallPeriodically(1000, 10000, self.InitiateSomeConnection)
		self.CallPeriodically(1, 200, self.SendSomeData)
		self.CallPeriodically(1, 50000, self.Echo)
		if RENEW_APP:
			self.CallPeriodically(10000, 300000,
					self.RenewApplication)

	def find_devices(self):
		adapter = self.manager.DefaultAdapter()
		adapter = bus.get_object("org.bluez", adapter)
		adapter = dbus.Interface(adapter, "org.bluez.Adapter")

		devices = adapter.ListDevices()
		for device_path in devices:
			device = bus.get_object("org.bluez", device_path)
			odevice = dbus.Interface(device, "org.bluez.Device")
			try:
				hdevice = dbus.Interface(device,
                                        "org.bluez.HealthDevice")
				hdevice.GetProperties()['MainChannel']
			except Exception:
				# device does not have health service class
				continue
			self.add_device(device_path, odevice, hdevice)

	def add_device(self, path, odevice, hdevice):
		props = odevice.GetProperties()
		addr = str(props['Address'])
		uuid = props['UUIDs']
		is_src = u'00001401-0000-1000-8000-00805f9b34fb' in uuid
		is_snk = u'00001402-0000-1000-8000-00805f9b34fb' in uuid

		# TODO filter (after fixing BlueZ problem)
		if is_src or is_snk:
			self.sources.append(path)
			self.Msg("Found source %s" % path)
		if is_snk or is_src:
			self.sinks.append(path)
			self.Msg("Found sink %s" % path)
		if is_src or is_snk:
			self.devices[path] = hdevice

	def CallSometime(self, lo, hi, cb, *args):
		to = lo + random.randint(lo, hi)
		self.CallLater(to, cb, *args)

	def CallLater(self, to, cb, *args):
		def closure(*args):
			cb(*args)
			return False
		glib.timeout_add(to, closure, *args)

	def CallPeriodically(self, lo, hi, cb, *args):
		def closure(*args):
			cb(*args)
			self.CallPeriodically(lo, hi, cb, *args)
			return False
		to = lo + random.randint(lo, hi)
		glib.timeout_add(to, closure, *args)

	def Dot(self, character="."):
		self.dot_count += len(character) + 1 
		print character, 
		sys.stdout.flush()
		if self.dot_count >= 80:
			self.dot_count = 0
			print

	def Msg(self, msg):
		if self.dot_count:
			print
			self.dot_count = 0
		print msg

	def Recv(self, sk, evt, *args):
		data = None
		if evt & glib.IO_IN:
			try:
				data = sk.recv(65535)
			except IOError:
				data = ""
			if data:
				self.Received(sk, data, *args)

		more = (evt == glib.IO_IN and data)

		if not more:
			self.EOF(sk, *args)

		return more

	def ChannelDot(self, path, msg):
		path = path.split("/")[-1]
		msg = msg % path
		self.Dot(msg)

	def MakeData(self, channel_path):
		self.data_seq += 1
		return self.channel_sig[channel_path] + " %d" % self.data_seq

	def CheckData(self, channel_path, data):
		expected = self.channel_sig[channel_path]
		ok = data[:len(expected)] == expected
		if not ok:
			self.Msg("%s %s %s" % (expected, data, channel_path))
		return ok

	def max_channels(self, device_path, seq):
		if not DISTINGUISH_APP:
			seq = 0

		if device_path not in self.chan_dev_app:
			self.chan_dev_app[device_path] = {}
			return False

		if seq not in self.chan_dev_app[device_path]:
			self.chan_dev_app[device_path][seq] = []
			return False

		return len(self.chan_dev_app[device_path][seq]) < MAX_CHANNELS

	def find_channels_device(self, channel_path):
		for device_path, apps in self.chan_dev_app.items():
			for apps, chanlist in apps.items():
				if channel_path in chanlist:
					return device_path
		return None

	######################################################################

	def EngageChannel(self, channel_path):
		self.ChannelDot(channel_path, "A:%s")
		try:
			fd = self.channels[channel_path].Acquire()
		except Exception:
			self.ChannelDot(channel_path, "AE:%s")
			return False

		# take fd ownership
		fd = fd.take()
		# encapsulate numericfd in Python socket object
		sk = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
		# fromfd() does dup() so we need to close the original
		os.close(fd)
		watch_bitmap = glib.IO_IN | glib.IO_ERR | glib.IO_HUP | glib.IO_NVAL
		glib.io_add_watch(sk, watch_bitmap, self.Recv, channel_path)

		if channel_path in self.sockets:
			self.sockets[channel_path].close()

		self.sockets[channel_path] = sk

		self.Dot("+%d" % sk.fileno())

		return True
		
	def Received(self, sk, data, channel_path):
		self.Dot('>%d' % sk.fileno())
		self.CheckData(channel_path, data)

	def EOF(self, sk, channel_path):
		self.CloseSocket(sk, channel_path)

		if random.randint(0, 10) == 0:
			# 10% chance of destroying channel
			self.DestroyChannel(channel_path)

	def CloseSocket(self, sk, channel_path):
		if sk.fileno() >= 0:
			self.Dot("-%d" % sk.fileno())
			try:
				sk.shutdown(2)
			except IOError:
				pass
			sk.close()

		if channel_path not in self.sockets:
			# we took the initiative of closing channel
			return

		del self.sockets[channel_path]


	def DestroyChannel(self, channel_path):
		self.ChannelDot(channel_path, "<xC:%s")

		if channel_path not in self.channels:
			# already destroyed
			self.Dot("dup")
			return

		device_path = self.find_channels_device(channel_path)
		device = self.devices[device_path]

		self.ForgetChannel(channel_path, device_path)

		device.DestroyChannel(channel_path,
			reply_handler=self.DestroyChannel_rsp,
			error_handler=self.DestroyChannel_err)

	def DestroyChannel_rsp(self):
		self.Dot("<xC")

	def DestroyChannel_err(self, *args):
		self.Dot("<xCe")

	def SendSomeData(self):
		if not self.channels:
			if self.retry_to > time.time():
				if not self.InitiateSomeConnection():
					self.retry_to = time.time() + 10
			else:
				return

		if not self.channels:
			return

		channel_path, channel = random.choice(self.channels.items())

		if channel_path not in self.sockets:
			# not connected at the moment
			self.ChannelDot(channel_path, "Re:%s")
			if not self.EngageChannel(channel_path):
				# failed to connect
				self.Dot("ReF")
				if random.randint(0, 2) == 0:
					self.Dot("ReDC")
					self.DestroyChannel(channel_path)
				return

		sk = self.sockets[channel_path]

		if random.randint(0, 99) == 0:
			# 1% chance of closing channel
			try:
				sk.shutdown(2)
			except IOError:
				pass

			self.CloseSocket(sk, channel_path)
			channel.Release()

			if random.randint(0, 2) == 0:
				# 33% chance of destroying upon closure
				self.ChannelDot(channel_path, "SSx:%s")
				self.DestroyChannel(channel_path)

		else:
			# just send data
			try:
				sk.send(self.MakeData(channel_path))
				self.Dot("<%d" % sk.fileno())
			except IOError:
				self.ChannelDot(channel_path, "SSe:%s")
				self.CloseSocket(sk, channel_path)
				channel.Release()

				if random.randint(0, 2) == 0:
					# 33% chance of destroying upon closure
					self.Dot("SSex")
					self.DestroyChannel(channel_path)

	def RememberChannel(self, accepted, channel_path, channel, device_path, app_path):
		appseq = self.apps.index(app_path)
		
		self.channels[channel_path] = channel
		if accepted:
			if channel_path not in self.accepted:
				self.accepted.append(channel_path)
		else:
			if channel_path not in self.initiated:
				self.initiated.append(channel_path)

		if device_path not in self.chan_dev_app:
			self.chan_dev_app[device_path] = {}

		chan_app = self.chan_dev_app[device_path]

		if appseq not in chan_app:
			chan_app[appseq] = []

		if channel_path not in chan_app[appseq]:
			chan_app[appseq].append(channel_path)

		data_type = 0x2000 + appseq // 2
		role = ["Source", "Sink"][appseq % 2]
		self.channel_sig[channel_path] = "%d %s" % (data_type, role)


	def ChannelConnected(self, channel_path, interface, device_path):
		self.ChannelDot(channel_path, ">C:%s")
		channel = bus.get_object("org.bluez", channel_path)
		channel = dbus.Interface(channel, "org.bluez.HealthChannel")

		try:
			props = channel.GetProperties()
		except Exception:
			self.ChannelDot(channel_path, ">Cpe")
			return

		if DISTINGUISH_APP:
			app_path = props['Application']
		else:
			app = self.apps[0]

		if app_path not in self.apps:
			# not our channel, or some error
			self.Dot("&")
			return

		self.RememberChannel(True, channel_path, channel, device_path, app_path)

		if not self.EngageChannel(channel_path):
			# if failed right after signal, destroy right now
			self.DestroyChannel(channel_path)
	
	def Echo(self):
		if self.echo_pending:
			return
		self.echo_pending = True
		self.Dot("H")
		device_path, device = random.choice(self.devices.items())
		device.Echo(reply_handler=self.Echo_2,
				error_handler=self.Echo_err)

	def Echo_2(self, res):
		self.echo_pending = False
		self.Dot(res and "h" or "hn")

	def Echo_err(self, *args):
		self.echo_pending = False
		self.Dot("HF")

	def ChooseDeviceApp(self):
		# Choose target device and application more or less randomly

		is_source = random.randint(0, 1)

		if not is_source:
			if not SINK_INITIATOR:
				is_source = 1
		if is_source:
			devs = self.sources
		else:
			devs = self.sinks

		if not devs:
			return False, False, None, None, None

		is_sink = 1 - is_source

		app0 = random.randint(0, MAX_APPS // 2 - 1)
		dev0 = random.randint(0, len(devs) - 1)

		for x in range(app0, app0 + MAX_APPS // 2):
			for y in range(dev0, dev0 + len(devs)):
				device_path = devs[y % len(devs)]
				seq = (x % (MAX_APPS // 2)) * 2 + is_sink
				if not self.max_channels(device_path, seq):
					return True, True, is_source, device_path, seq

		return False, True, None, None, None

	def InitiateSomeConnection(self):
		# Initiates a connection with some given device

		ok, res, is_source, device_path, seq = self.ChooseDeviceApp()

		if not ok:
			# all devices/apps fully connected
			return res

		device = self.devices[device_path]

		# Sinks can not choose
		config = "Any"
		if is_source:
			if device_path in self.channels:
				config = random.choice(["Reliable", "Streaming"])
			else:
				# First must be reliable
				config = "Reliable"

		self.ChannelDot(device_path, "@%s")
		device.CreateChannel(self.apps[seq], config,
					reply_handler=self.CreateChannel_rsp,
					error_handler=self.CreateChannel_err)

		return True

	def CreateChannel_err(self, *args):
		self.Dot('<Ce')

	def CreateChannel_rsp(self, channel_path):
		channel = bus.get_object("org.bluez", channel_path)
		channel = dbus.Interface(channel, "org.bluez.HealthChannel")

		self.ChannelDot(channel_path, "<C:%s")

		try:
			props = channel.GetProperties()
		except Exception:
			self.ChannelDot(channel_path, "<Cpe")
			return

		device_path = props['Device']
		if DISTINGUISH_APP:
			app_path = props['Application']
		else:
			app_path = self.apps[0]

		self.RememberChannel(True, channel_path, channel, device_path, app_path)

		self.EngageChannel(channel_path)
		# do not destroy it if it fails the first time.

	def ChannelDeleted(self, channel, interface, device_path):
		self.ChannelDot(channel, ">xC:%s")
		if channel not in self.channels:
			# already destroyed by us
			self.Dot("dup")
			return

		self.ForgetChannel(channel, device_path)

	def DevicePropertyChanged(self, prop, value, interface, device_path):
		if prop == "MainChannel":
			self.ChannelDot(value, "main:%s")

	def ForgetChannel(self, channel, device):
		try:
			self.accepted.remove(channel)
		except ValueError: 
			pass

		try:
			self.initiated.remove(channel)
		except ValueError: 
			pass

		if device in self.chan_dev_app:
			apps = self.chan_dev_app[device]
			for app, channels in apps.items():
				if channel in channels:
					channels.remove(channel)
					break

		if channel in self.sockets:
			self.CloseSocket(sk, channel)

		if channel in self.channel_sig:
			del self.channel_sig[channel]

		del self.channels[channel]

	def Decode(self, n):
		data_type = 0x2000 + n // 2
		role = ["Source", "Sink"][n % 2]
		channel_type = None
		if n >= 2 and role == "Source":
			channel_type = ["Reliable", "Streaming"][(n // 2) % 2]
		print "Application %d: type %d role %s ct %s" % \
						(n, data_type, role, channel_type)
		return data_type, role, channel_type

	def CreateApplications(self):
		if self.apps:
			raise Exception("Applications already created")

		for x in range(0, MAX_APPS):
			self.apps.append(None)
			self.CreateApplication(x)

	def CreateApplication(self, seq):
		data_type, role, channel_type = self.Decode(seq)

		config = {"Role": role,
			"DataType": dbus.types.UInt16(data_type),
			"Description": "Type %d role %s" % (data_type, role),
			}

		if channel_type:
			config['ChannelType'] = channel_type

		app_path = self.hmanager.CreateApplication(config)
		# app = bus.get_object("org.bluez", app_path)
		# app = dbus.Interface(app, "org.bluez.HealthApplication")
		self.apps[seq] = app_path

		self.Msg('Application %s created' % app_path)

	def DestroyApplication(self, seq):
		path = self.apps[seq]
		self.hmanager.DestroyApplication(path)
		self.apps[seq] = None
		self.Msg('Application %s destroyed' % path)

	def RenewApplication(self):
		victim = random.randint(0, MAX_APPS - 1)
		self.DestroyApplication(victim)
		self.CreateApplication(victim)
		self.Msg('Renewing application')


mcp = MasterControl()

loop = glib.MainLoop()
loop.run()

# -s
#	Silent. Do not search devices and do not try to connect.
#	Useful in pairing phase, when devices learn each other's service class
