#!/usr/bin/python

import sys
import dbus
import time
import gobject
import dbus.mainloop.glib
from mcap.misc import parse_params

mcap_iface = "org.bluez.mcap"

def object_signal(*args, **kwargs):
	print "Value", args
	print "Details", kwargs

dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.bluez", "/"), "org.bluez.Manager")

adapter, device, cpsm, dpsm, addr = parse_params(sys.argv, False)

ad = manager.FindAdapter(adapter)
print "Binding to adapter", ad

adapter = dbus.Interface(bus.get_object("org.bluez", ad), mcap_iface)

bus.add_signal_receiver(object_signal, bus_name="org.bluez",
				member_keyword="member",
				path_keyword="path",
				interface_keyword="interface",
				dbus_interface=mcap_iface,
				byte_arrays=True)

handle = adapter.StartSession(cpsm + 0x10, dpsm + 0x10)

try:
	print "Handle: ", handle

	mcl = adapter.CreateMCL(handle, device, cpsm)

	mdl = adapter.CreateMDL(mcl, 0x01, 0x00)
	adapter.ConnectMDL(mdl, dpsm)
	adapter.Send(mdl, "teste")

	mainloop = gobject.MainLoop()
	mainloop.run()

finally:
	adapter.StopSession(handle)
	print
	print "Stopped instance, thanks"
	print
