#!/usr/bin/env python
# -*- coding: utf-8

#######################################################################
# Copyright 2010 Signove Corporation - All rights reserved.
# Contact: Signove Corporation (contact@signove.com)
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of version 2.1 of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330,
# Boston, MA 02111-1307  USA
#
# If you have questions regarding the use of this file, please contact
# Signove at contact@signove.com.
#######################################################################

from hdp import hdp_record
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object("org.bluez", "/"),
						"org.bluez.Manager")

adapter_list = manager.ListAdapters()

for i in adapter_list:
	adapter = dbus.Interface(bus.get_object("org.bluez", i),
							"org.bluez.Adapter")
	properties  = adapter.GetProperties()
	try:
		device_list = properties["Devices"]
	except:
		device_list = []

	for n in device_list:
		device = dbus.Interface(bus.get_object("org.bluez", n),
							"org.bluez.Device")
		p = device.GetProperties()
		print "Discovering device", p['Address'], p['Name']
		try:
			services = device.DiscoverServices("")
		except:
			services = {}

		for handle in services.keys():
			hdp = hdp_record.parse_xml(services[handle])
			if hdp:
				print "Handle %08x:" % handle
				print hdp_record.parse_xml(services[handle])
